### ISSUE TITLE
Non-debug compilation fails (Android)

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#401]
../src/os/host-main.c: In function 'main':
../src/os/host-main.c:686:12: error: 'SIGINT' undeclared (first use in this function)
     signal(SIGINT, Handle_Signal);
            ^
../src/os/host-main.c:686:12: note: each undeclared identifier is reported only once for each function it appears in
../src/os/host-main.c:690:12: error: 'SIGTERM' undeclared (first use in this function)
     signal(SIGTERM, Handle_Signal);
            ^
../src/os/host-main.c:694:12: error: 'SIGHUP' undeclared (first use in this function)
     signal(SIGHUP, Handle_Signal);
            ^
make: *** [objs/host-main.o] Error 1

NOTE: affects only Android, with -DNDEBUG

**Comment by giuliolunati** [comment]
Introduced in b7e2678

**Comment by hostilefork** [comment]
Well, in C sometimes you #include something and then under certain circumstances that will #include other things implicitly, but then in other circumstances it won't.  I guess something about an Android system file that gets depended on will include signal.h in a debug build but not a release build... but this is why you're supposed to be explicit when you can.

Hopefully this resolves it:

https://github.com/metaeducation/ren-c/commit/3cbab012366b2771507c40e58b6250b0b28ccd96

**Comment by giuliolunati** [comment]
Ok, works!
